---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-recordings
spec:
  storageClassName: "perturabo-smb"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: $VOLUMEID # make sure it's a unique id in the cluster
    volumeAttributes:
      source: $SOURCE
    nodeStageSecretRef:
      name: smb-creds
      namespace: smb-test
