---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: game-recordings-smb
spec:
  storageClassName: "perturabo-smb"
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: perturabo.${FAMILY_DOMAIN}/videos##
    volumeAttributes:
      source: //perturabo.${FAMILY_DOMAIN}/videos
    nodeStageSecretRef:
      name: talos-smb-cred
      namespace: media
