---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emberstone-database
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: codex-block
  resources:
    requests:
      storage: 10Gi
