---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ddns-client
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-client
spec:
  concurrencyPolicy: Forbid
  schedule: '*/45 * * * *' # Every hour at 45 minutes past the hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 60
  timeZone: "${LOCAL_TIMEZONE}"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: ddns-client
          restartPolicy: Never
          containers:
            - name: ddns-client
              image: ghcr.io/timothyye/godns:v3.4.2@sha256:2ae70a3b5dcb2a52202e1e2dd7ce4d0d8cf5f5727d06c33f2f506cc199851a28
              volumeMounts:
                - name: ddns-config
                  mountPath: /config.json
                  subPath: config.json
                  readOnly: true
          volumes:
            - name: ddns-config
              secret:
                secretName: ddns-config
