---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: ddns-client
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: ddns-client
spec:
  concurrencyPolicy: Forbid
  schedule: '*/45 * * * *' # Every hour at 45 minutes past the hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 60
  timeZone: "${LOCAL_TIMEZONE}"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: ddns-client
          restartPolicy: Never
          containers:
            - name: ddns-client
              image: ghcr.io/timothyye/godns:v3.3.4@sha256:a180f8b10f16bab08e2e01fc042fe614086766ece78c714da222657b94f95495
              volumeMounts:
                - name: ddns-config
                  mountPath: /config.json
                  subPath: config.json
                  readOnly: true
          volumes:
            - name: ddns-config
              secret:
                secretName: ddns-config
