---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: windrose-data
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: terra-block
  resources:
    requests:
      storage: 20Gi
