---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bewcloud-data-smb
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: bewcloud-data-smb
    namespace: home
  csi:
    driver: smb.csi.k8s.io
    nodeStageSecretRef:
      name: talos-smb-cred
      namespace: home
    volumeAttributes:
      source: //perturabo.heyjohn.family/bewcloud
    volumeHandle: perturabo.heyjohn.family/bewcloud##
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: perturabo-smb
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bewcloud-data-smb
  namespace: home
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Ti
  storageClassName: perturabo-smb
  volumeMode: Filesystem
  volumeName: bewcloud-data-smb
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Ti
