<?php
$config["baseurl"] = "https://rgcraft.heyjohn.family";
$config["page_title"] = "RGCraft";
$config["language"] = "english";
$config["supported_langs"] = [
  "english" => "English",
];
$config["debug_mode"] = false;
$config["realmlist"] = "acore.heyjohn.family:3725";
$config["patch_location"] = "";
$config["game_version"] = "3.3.5a";
$config["expansion"] = "2";
$config["server_core"] = 1;
$config["battlenet_support"] = false;
$config["srp6_support"] = true;
$config["srp6_version"] = 0;
$config["template"] = "kaelthas";
$config["captcha_type"] = 0;
$config["captcha_key"] = "";
$config["captcha_secret"] = "";
$config["captcha_language"] = "en";
$config["soap_for_register"] = false;
$config["soap_host"] = "acore-soap";
$config["soap_port"] = "7878";
$config["soap_uri"] = "urn:AC";
$config["soap_style"] = "SOAP_RPC";
$config["soap_username"] = "soapadmin";
$config["soap_password"] = "soapadmin";
$config["soap_ca_command"] = "account create {USERNAME} {PASSWORD}";
$config["smtp_host"] = "";
$config["smtp_port"] = 587;
$config["smtp_auth"] = false;
$config["smtp_user"] = "";
$config["smtp_pass"] = "";
$config["smtp_secure"] = "tls";
$config["smtp_mail"] = "";
$config["vote_system"] = false;
$config["vote_sites"] = [];
$config["2fa_support"] = false;
$config["soap_2d_command"] = "account set 2fa {USERNAME} off";
$config["soap_2e_command"] = "account set 2fa {USERNAME} {SECRET}";
$config["db_auth_host"] = "acore-database";
$config["db_auth_port"] = "3306";
$config["db_auth_user"] = "root";
$config["db_auth_pass"] = "password";
$config["db_auth_dbname"] = "acore_auth";
$config["realmlists"] = [
  "1" => [
    "realmid" => 1,
    "realmname" => "RGCraft",
    "db_host" => "acore-database",
    "db_port" => "3306",
    "db_user" => "root",
    "db_pass" => "password",
    "db_name" => "acore_characters",
  ],
];
$config["disable_changepassword"] = true;
$config["disable_top_players"] = true;
$config["disable_online_players"] = false;
$config["multiple_email_use"] = true;
$config["script_version"] = "2.0.4";
