---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/charts/refs/tags/cloudnative-pg-v0.28.2/charts/cluster/values.schema.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres18
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9187"
spec:
  instances: 2
  env:
    - name: TZ
      value: "${LOCAL_TIMEZONE}"
  # imageName: ghcr.io/cloudnative-pg/postgresql:18.3
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:18.3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 30Gi
    storageClass: codex-block
  enableSuperuserAccess: true
  superuserSecret:
    name: cnpg-superuser
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "400"
      shared_buffers: 256MB
  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: false
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: b2-${CLUSTER_ITERATION_PRESENT}
  bootstrap:
    recovery:
      source: previous
  # Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: previous
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: b2-${CLUSTER_ITERATION_PREVIOUS}
          serverName: ${CLUSTER_ITERATION_PREVIOUS}
