---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - barmanobjectstore.yaml
  - b2.enc.yaml
  - superuser.enc.yaml
  - service.yaml
  - cluster.yaml
  - scheduled-backup.yaml
