apiVersion: v1
stringData:
    dbname: ENC[AES256_GCM,data:pQ==,iv:cXS0K4X9C92if4ugzk7MDGZV+tVddB7NsTh2HrPqUj8=,tag:nWpZd2RGQSQkXkpvp9uygg==,type:str]
    host: ENC[AES256_GCM,data:75TfOX5E/6gNkVY=,iv:VU4QVXP1S2T2g8uyw00jPQxS94lNtc3gCKu5Lrq1UPs=,tag:dNejEYVPybLybBzTnJAeyg==,type:str]
    jdbc-uri: ENC[AES256_GCM,data:/Ioxq2dLWyX1X7dW/hdyGDcldVejn8+t59rhxIDw2yWEIiF2RGSDIjvutWezIT1WljkgChgtnnggpsZKw8dadIxZPb1OxJbZ/HPUF8cNvazA8Ixsy+Bx7fRvOhIqr+IxSEOKOdfXLzqwhqEVDBespGrPAcllFMSDd3G2ycPeNxMSomUITQ==,iv:kmL0HhendwX6ozuTvFfBkd9w271Dh1t8QnUjNY0ES6A=,tag:JYoH+sBgDlyFfcyJPRmZeQ==,type:str]
    password: ENC[AES256_GCM,data:hd8Wrpb/H0D77bWRAeNX7QT8AODKf6oTiGs1CeYF/ODLCDJzQ0gHdTI4OQAG187nR8wszBPAGM6k9o8gQ8Fz3g==,iv:QJ/nG26rTluUXC0uifSViSKIydeqrlFbxi+6b44ZR/0=,tag:9RVVZpw5LcqpnfzGkKOB2w==,type:str]
    pgpass: ENC[AES256_GCM,data:GkXojTj+rHmPsmUwW2Zc/97m481acEuENOCYoHbajc9BU4m61a4MicJz2ETUngx9xk1DbclgF+H5Jh8H54ImBpXZ4onyrN9gjc7G9v3pVkw3+3aPqTM6+RgM46I=,iv:gOiAm1laMBwgHK8CYKjrKFVDSIOTJ/qmCB140Opd6UU=,tag:D/3x9jTbd4squguNBS+QdA==,type:str]
    port: ENC[AES256_GCM,data:owpvYw==,iv:0jHhRlF+P5TbxtcgPs6feQtyjRa8uomWzYBGLV7RfAA=,tag:g/zGqg65QsF4tLAHjVaa5Q==,type:str]
    uri: ENC[AES256_GCM,data:EgTMxJ16eHsU8BmN8UUQ9kj/DLgjRndM25u6QDnGe8nAfHzXO22aTIJGdz9puXXnlOFWsdLxYsgyBJF/EnPXxjpvuz/sm8ac0SDcjFgUlB/bIcCW3GYA9z2dqaQStpNaA9vf13ikSnFneQzbDCjxqW76,iv:HnIm0bVaGlhYIpXR4p5IJCQnn76WoJhMeFU/70sFY1U=,tag:60JVjRIyLpAfnjNqbi1+VQ==,type:str]
    user: ENC[AES256_GCM,data:k1Xm+tgLKOk=,iv:R7zXODTdmtVUUH64JQBCVC64YAXQFqgGoSM5z1fxe4k=,tag:oUiUxYF+2SIbhhh/m5amwA==,type:str]
    username: ENC[AES256_GCM,data:uYK+VweKpdk=,iv:5djZiSkxcnP96/aZwoPWhNHVrD6IrXgZjH1/RKStoYQ=,tag:qn44otON3RbS3v/pF44OfA==,type:str]
kind: Secret
metadata:
    annotations:
        cnpg.io/operatorVersion: 1.23.3
    labels:
        cnpg.io/cluster: postgres18
        cnpg.io/reload: "true"
    name: cnpg-superuser
type: kubernetes.io/basic-auth
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:300851077188:key/b797e748-1c53-462c-9c4c-50eebebc3130
          created_at: "2024-08-21T03:12:28Z"
          enc: AQICAHjVtcO/v540ZKcn1JNHjpqxHudubzP0wst32mS/Cuj1RwEz5qGd29k0ChJjHaZKHBbrAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4nkbUORsk1rXv7w/AgEQgDu/IoTEWtX1E1CFTYOBlkwGXAON9qKLueyu0+JD/6frlos3wQ+pQvND77uZHDv0u4hxO9pcdj7iq5sdWw==
          aws_profile: ""
    lastmodified: "2026-05-20T03:33:42Z"
    mac: ENC[AES256_GCM,data:+fodxV8h9r8WMPCq5y1wPfC6ctY16e2AWgU4Pg+WYzB0fIHl9BKrkURGZUyqd8gfbZOYq67/itLqf0a9gidvAeyuPOI+/NhGCZWaejngc4rNB6rPAnDCQ5u2UQTc0ongjdNvP0wghJY3cKp1/cpkIta682M8Nqo5B0ZhuTqNzMc=,iv:8iX8KJLYVteif074cL8P15WkgiGI5qYX9iIuePyrbEE=,tag:ZHdhNcm/ABkoj08niEsuSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
