---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azerothcore-cores
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: codex-file
  resources:
    requests:
      storage: 40Gi
