# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 12h
  timeout: 30m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      ${APP}:
        containers:
          ${APP}:
            image:
              repository: ghcr.io/xunholy/cmangos-registration
              tag: da24e639b3b8e8366f792423399cb8ef0ca2f4b7
            env:
              TZ: ${LOCAL_TIMEZONE}
            probes:
              liveness:
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  periodSeconds: 30
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness:
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 3
              startup:
                enabled: false
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 80
                  periodSeconds: 10
                  timeoutSeconds: 3
                  failureThreshold: 30
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        fsGroup: 33
        fsGroupChangePolicy: OnRootMismatch

    ingress:
      ${APP}:
        annotations:
          external-dns/public: "true"
          opn.internal-dns.kubernetes.io/target: &target external-ingress.${SECRET_DOMAIN}
          opn.internal-dns.kubernetes.io/hostname: &hostname ${INGRESSROUTE_SUBDOMAIN}.${FAMILY_DOMAIN}
          pi.internal-dns.kubernetes.io/target: *target
          pi.internal-dns.kubernetes.io/hostname: *hostname
          gandi.external-dns.kubernetes.io/target: ${DYNAMIC_DOMAIN}
          gandi.external-dns.kubernetes.io/hostname: *hostname
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        labels: {}
        className: traefik-external
        hosts:
          - host: *hostname
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: ${APP}
                  port: 80
        tls:
          - secretName: heyjohn-wildcard-certificate
            hosts:
              - *hostname

    service:
      ${APP}:
        controller: ${APP}
        ports:
          http:
            port: 80
    persistence:
      config:
        type: configMap
        name: azerothcore-registration-config
        advancedMounts:
          ${APP}:
            ${APP}:
              - path: /var/www/html/application/config/config.php
                subPath: config.php
              - path: /var/www/html/template/kaelthas/tpl/posts.php
                subPath: posts.php
              - path: /var/www/html/template/kaelthas/tpl/howtoconnect.php
                subPath: howtoconnect.php
              - path: /var/www/html/template/kaelthas/tpl/header.php
                subPath: header.php
              - path: /var/www/html/template/kaelthas/tpl/footer.php
                subPath: footer.php
