# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/tags/common-3.1.0/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 12h
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      runtimeClassName: "nvidia"
      tolerations:
        - effect: NoSchedule
          key: nvidia.com/gpu
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      # securityContext:
      #   fsGroup: ${APP_UID}
      #   runAsNonRoot: true
      #   runAsUser: ${APP_UID}
      #   runAsGroup: ${APP_UID}

    controllers:
      vllm:
        type: deployment
        containers:
          vllm:
            nameOverride: vllm
            image:
              repository: vllm/vllm-openai
              tag: latest@sha256:2296a2a7e1ce1dc59c6577ba5900f4e9910b76c4a0cb134833a8137f92404dfa
            env:
              TZ: America/New_York
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            args: ["vllm", "serve", "--config", "/config/vllm.yaml"]
            resources:
              requests:
                cpu: 4
                memory: 24Gi
                nvidia.com/gpu: "1"
              limits:
                nvidia.com/gpu: "1"
    service:
      vllm:
        enabled: true
        controller: vllm
        primary: true
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        labels:
          io.cilium/bgp-announce: worker
        annotations:
          io.cilium/lb-ipam-ips: "${CLUSTER_LB_OLLAMA}"
        ports:
          vllm:
            port: 8000

    ingress:
      main:
        enabled: false
        hosts: []

    persistence:
      shm:
        type: emptyDir
        medium: Memory
        sizeLimit: 10Gi
        globalMounts:
          - path: /dev/shm
      vllm-data:
        enabled: true
        existingClaim: "vllm-data"
        globalMounts:
          - path: /root/.cache/huggingface
            readOnly: false
      config-file:
        type: configMap
        name: vllm-config
        globalMounts:
          - path: /config/vllm.yaml
            subPath: vllm.yaml
            readOnly: true
