---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: hugoprudente-charts
  namespace: flux-system
spec:
  interval: 2h
  ignore: |
    # exclude all
    /*
    # include chart dir
    !/incubator/
  url: https://github.com/hugoprudente/charts
  timeout: 3m
  ref:
    commit: 361f56b2f7dbc7f5d81f962a72c4c92140329eff
