---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocis-charts
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # path to chart
    !/charts/ocis
  interval: 5h
  ref:
    commit: b233a407b004a92d7d0824cdc061db087db0f751
  timeout: 60s
  url: https://github.com/owncloud/ocis-charts.git
