---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocis-charts
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # path to chart
    !/charts/ocis
  interval: 5h
  ref:
    commit: aeb5a0b6d93b06fa2a0f96a163e57d07548979b7
  timeout: 60s
  url: https://github.com/owncloud/ocis-charts.git
