---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocis-charts
  namespace: flux-system
spec:
  ignore: |
    # exclude all
    /*
    # path to chart
    !/charts/ocis
  interval: 5h
  ref:
    commit: c5d8e8bf1e5a5b652a258105f373dc937a72fc45
  timeout: 60s
  url: https://github.com/owncloud/ocis-charts.git
