---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manyfold-plugins
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: terra-block
