---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcast-library
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: codex-block
  resources:
    requests:
      storage: 10Gi
