---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: music-library-smb
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1512Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: music-library-smb
    namespace: media
  csi:
    driver: smb.csi.k8s.io
    nodeStageSecretRef:
      name: talos-smb-cred
      namespace: media
    volumeAttributes:
      source: //perturabo.heyjohn.family/music
    volumeHandle: perturabo.heyjohn.family/music##
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: perturabo-smb
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-library-smb
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1512Gi
  storageClassName: perturabo-smb
  volumeMode: Filesystem
  volumeName: music-library-smb
status:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1512Gi
