---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 12h
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      ${APP}:
        type: deployment

        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: ${APP}-env

        containers:
          ${APP}:
            nameOverride: ${APP}
            args:
              - "--config"
              - "/app/proxy_config.yaml"
            image:
              repository: ghcr.io/berriai/litellm
              tag: v1.83.14-stable@sha256:c81eb79cd4333c6cfe374c0ec929110fd23f0ee5f7fd198855a6fbddc77b83ba
            env:
              TZ: ${LOCAL_TIMEZONE}
            envFrom: *envFrom
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/liveliness
                    port: 4000
                  initialDelaySeconds: 120
                  periodSeconds: 15
                  successThreshold: 1
                  failureThreshold: 3
                  timeoutSeconds: 10
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health/readiness
                    port: 4000
                  initialDelaySeconds: 120
                  periodSeconds: 15
                  successThreshold: 1
                  failureThreshold: 3
                  timeoutSeconds: 10
              startup:
                enabled: false
            resources:
              requests:
                cpu: 47m
              limits:
                memory: 8Gi

    # defaultPodOptions:
    #   securityContext:
    #     runAsNonRoot: true
    #     runAsUser: 994
    #     runAsGroup: 994
    #     fsGroup: 994
    #     fsGroupChangePolicy: OnRootMismatch
    #     seccompProfile: { type: RuntimeDefault }

    ingress:
      ${APP}:
        # controller: "${APP}"
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ${INGRESSROUTE_SUBDOMAIN}.${FAMILY_DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${CLUSTER_LB_INGRESS_INTERNAL}
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          # traefik.ingress.kubernetes.io/router.middlewares: auth-system-oauth-auth@kubernetescrd,auth-system-oauth-errors@kubernetescrd
        labels: {}
        className: traefik-internal
        hosts:
          - host: ${INGRESSROUTE_SUBDOMAIN}.${FAMILY_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: ${APP}
                  port: 4000
        tls:
          - secretName: heyjohn-wildcard-certificate
            hosts:
              - ${INGRESSROUTE_SUBDOMAIN}.${FAMILY_DOMAIN}

    service:
      ${APP}:
        enabled: true
        controller: ${APP}
        primary: true
        ports:
          http:
            port: 4000
      ${APP}-db:
        enabled: true
        controller: ${APP}
        primary: false
        ports:
          db:
            port: 5432

    persistence:
      config-file:
        type: configMap
        name: ${APP}-config
        advancedMounts:
          ${APP}:
            ${APP}:
              - path: /app/proxy_config.yaml
                subPath: config.yaml
                readOnly: true
      db-data:
        existingClaim: ${APP}-db-data
        advancedMounts:
          ${APP}:
            ${APP}-db:
              - path: /var/lib/postgresql/data
