---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acore-scripts
  namespace: games
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: codex-file
  resources:
    requests:
      storage: 10Gi
