---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: android-dav
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: terra-file
