---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-data
  namespace: home
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: terra-block
