---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: nord
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: &aRecord nixos-ord.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: A
      targets:
        - 100.64.0.11
    - dnsName: prometheus.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: alerts.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: alerts.ord.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: alertmanager.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: prom.ord.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: prometheus.ord.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: nord.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: grafana.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: grafana.ord.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: loki.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
    - dnsName: loki.ord.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *aRecord
