---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pihole
  annotations:
    external-dns/private: "true"
spec:
  endpoints:
    - dnsName: &pi1 peanut1.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: A
      targets:
        - 192.168.130.2
    - dnsName: &pi2 peanut2.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: A
      targets:
        - 192.168.130.3
    - dnsName: pihole1.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *pi1
    - dnsName: pihole2.${FAMILY_DOMAIN}
      recordTTL: 0
      recordType: CNAME
      targets:
        - *pi2
