apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: android-dav-env
stringData:
    BASIC_AUTH_ENABLED: ENC[AES256_GCM,data:2CCFEA==,iv:A0K/K1M2TMoEs7395YfWwlBs5ox+Q3Bm6CILFrytozU=,tag:CGBw1qaFKBiGDa93rwRHLw==,type:str]
    DIGEST_AUTH_ENABLED: ENC[AES256_GCM,data:YrZmufk=,iv:H910kcJgb4ONS4J3IVUGdLrTi91lQ13M2d2eoSTDmqQ=,tag:xyDCAHNzbC/jiWe/gAq2ww==,type:str]
    BASIC_USERS: ENC[AES256_GCM,data:198kpS9Lw5ky2cjVo2vX7MPhDB/hjccLKt63eQJtLsBKti1E,iv:ClFkrzqnBgD0KocH4QuJ+gEAhETzihnI04gN6//uVGc=,tag:MXTOtUEfPIPWasu3MGO+8A==,type:str]
    RO_METHODS: ENC[AES256_GCM,data:MEE7b43d2OyliaC4y+3KwDB/Yxqk6zEOgA==,iv:xFrQaQpMODNlC8/zFMHYGI2ActpaxfTZlnvIaIHGLwM=,tag:CYznZQDEQl9gps1Q+3ex+g==,type:str]
    RW_METHODS: ENC[AES256_GCM,data:/mwszV6bHN0HXwdM+bVMfBWbFwmIIx0+9cI0P/jTVrCMMixW/HI7EHHzGqd1t+y2UutZTRhcEE1kQnZ7UaqgzqSeR4y42IC2GH0=,iv:enR7lAEqfpZMFrq6oL0qrlpbfqUa5kJBzj5Hfed2EeI=,tag:ixT+QgkbC44va9SOMRCELw==,type:str]
    SERVER_NAME: ENC[AES256_GCM,data:RSKLoAJU2qrpOxizyoOwB72TiDZClve8JmY=,iv:bLJsbNz9StU+D4cDgE+6coabIslJMCThEAK0IjsVrr8=,tag:00OshTyx3CpniG4CZ+QKsg==,type:str]
    CORS_ENABLED: ENC[AES256_GCM,data:cFYN6w==,iv:/d9PoDlpjxLvylOyWgoeyR1XAuhfdQaSxvD+0Nu0H0c=,tag:/bYZ0SUIwvaPuAuLomlrKg==,type:str]
    CORS_ORIGIN: ENC[AES256_GCM,data:3gxv56BQXRo8t8uaut05E0dOlUnG8QSfdtSIGrNnanpoww==,iv:7K3+hbNGbbn6HrdIzH1U/yGD0GAUISBYgvSYCh888L8=,tag:DVN8fckyBrkMfpuppiFx0Q==,type:str]
    HEALTH_CHECK_ENABLED: ENC[AES256_GCM,data:I+3nyOA=,iv:ziWOogichoQFb86KfHuzxCa3o8C27ZoM+9Q+0pgXCfY=,tag:NpC9/GnY6mxbd/c/MY5Qdg==,type:str]
    FOLDER_PERMISSIONS: ENC[AES256_GCM,data:YBSS8JiEDK9KydjJC2Cq9Y2YZrcSOr9ckT8=,iv:urr5FNK5cwm1XDPIq3gczOPn0PlXsXuDl5BorcdEqJA=,tag:KtFn3G7UmnVb4clXGeFFFQ==,type:str]
    AUTO_CREATE_FOLDERS: ENC[AES256_GCM,data:iG9eqw==,iv:d3qR2zzG2lkMjbT7w8s+y+s+eZlq1SYYZTANl4JdsyE=,tag:synUfrXBJKmO7xLHYLLOQg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:300851077188:key/b797e748-1c53-462c-9c4c-50eebebc3130
          created_at: "2026-05-02T19:57:18Z"
          enc: AQICAHjVtcO/v540ZKcn1JNHjpqxHudubzP0wst32mS/Cuj1RwFrmzSKZZ/Jr6v5snBQ+8uxAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMVg/0BuAh6epgmkFtAgEQgDuaxRoO65axz90oDH0zEjLxXp0F6fCqGM1hWQlR7b1S2uJ2QNu6qNjCUY7YpAtlR4tS7osJ7JYQeJ0NMQ==
          aws_profile: ""
    lastmodified: "2026-05-03T00:51:16Z"
    mac: ENC[AES256_GCM,data:I0AKf0fRZTkFwrpEmDFzfAPJ7vgqkNt8zIjFaTZlFzKcHroEAN0hC1mCOuRbOPXvC4gPraTqhBSA4biI6RqIABw5wDKZ3NLRpnJBxjlX/VefWUPUQtCjz3sCEoL+RYnbZwXtZu526YfHV+GDPCquXOtM06K0kz1G+pk+wy3st6E=,iv:vY6k968E6l1lFAuB/JzCF7NnDrimY2sXxsKER7/b1Xs=,tag:O0YkYTqUPFb6LoFQuJ/V7Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
