---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${APP}
spec:
  interval: 12h
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      securityContext:
        fsGroup: ${APP_UID}
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      android-dav:
        annotations:
          secret.reloader.stakater.com/reload: android-dav-env

        containers:
          android-dav:
            image:
              repository: ghcr.io/vaggeliskls/webdav-server
              tag: 2.3.0@sha256:4b966d6041c070d394bbf783091354512780627533717e3b3b0ab5be72cc74ee
            probes:
              liveness:
                enabled: false
                type: TCP
                spec:
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: false
                type: TCP
                spec:
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: false
                type: TCP
                spec:
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            envFrom:
              - secretRef:
                  name: android-dav-env
            resources:
              requests:
                cpu: 5m
                memory: 512Mi
              limits:
                memory: 1Gi
            # securityContext:
            #   allowPrivilegeEscalation: false
            #   readOnlyRootFilesystem: false
            #   capabilities:
            #     drop:
            #       - ALL

    ingress:
      android-dav:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: ${INGRESSROUTE_SUBDOMAIN}.${FAMILY_DOMAIN}
          external-dns.alpha.kubernetes.io/target: ${CLUSTER_LB_INGRESS_INTERNAL}
        labels: {}
        className: traefik-internal
        hosts:
          - host: ${INGRESSROUTE_SUBDOMAIN}.${FAMILY_DOMAIN}
            paths:
              - path: /
                pathType: ImplementationSpecific
                service:
                  name: android-dav
                  port: 8080
        tls:
          - secretName: heyjohn-wildcard-certificate
            hosts:
              - ${INGRESSROUTE_SUBDOMAIN}.${FAMILY_DOMAIN}

    service:
      android-dav:
        controller: android-dav
        primary: true
        ports:
          http:
            port: 8080

    persistence:
      data:
        existingClaim: android-dav
        advancedMounts:
          android-dav:
            android-dav:
              - path: /var/lib/dav
