machine:
  nodeLabels:
    heyjohn.family/ceph: terra
    heyjohn.family/role: nas
    heyjohn.family/rook: single
  certSANs:
    - 192.168.130.140
    - fulgrim.heyjohn.family
    - fulgrim
  install:
    disk: /dev/disk/by-id/nvme-TEAM_TM8FP6001T_TPBF2110010090200660
  kernel:
    modules:
      - name: nvidia
      - name: nvidia_uvm
      - name: nvidia_drm
      - name: nvidia_modeset
  sysctls:
    net.core.bpf_jit_harden: 1
  files:
    - op: create
      path: /etc/cri/conf.d/20-customization.part
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
          [plugins."io.containerd.cri.v1.runtime".containerd]
            default_runtime_name = "nvidia"
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: mac(link.permanent_addr).matches("98:b7:85:1e:d8:ad")
