machine:
  nodeLabels:
    heyjohn.family/ceph: codex
    heyjohn.family/rook: distributed
  certSANs:
    - 192.168.130.142
    - sanguinius.heyjohn.family
    - sanguinius
  install:
    disk: /dev/disk/by-id/nvme-CT1000P3SSD8_24244963E274
  files:
    - op: create
      path: /etc/cri/conf.d/20-customization.part
      content: |
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: mac(link.permanent_addr).matches("58:47:ca:76:b6:f1")
